app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$uploadFile(datafile = "example.xlsx")
app$setInputs(do = "click")
app$setInputs(df_rows_current = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_rows_all = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_state = c(1660142380445, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(`selected.columns` = "Apple")
app$setInputs(`selected.columns` = c("Apple", "Lemon"))
app$setInputs(`date.input` = "4")
app$setInputs(`date.input` = "5")
app$setInputs(do = "click")
app$setInputs(df_rows_current = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_rows_all = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_state = c(1660142389601, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$snapshot()
app$setInputs(`selected.columns` = "Apple")
app$setInputs(`selected.columns` = c("Apple", "Pear"))
app$setInputs(`selected.columns` = c("Apple", "Pear", "Lemon"))
app$setInputs(do = "click")
app$setInputs(df_rows_current = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_rows_all = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_state = c(1660142401478, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$snapshot()
app$snapshot()
app$snapshotDownload("downloadData")
