app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$uploadFile(datafile = "example.xlsx") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$snapshot()
app$setInputs(do = "click")
app$setInputs(df_rows_current = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_rows_all = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_state = c(1660138074173, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$snapshot()
app$setInputs(`selected.columns` = "Apple")
app$setInputs(`selected.columns` = c("Apple", "Pear"))
app$setInputs(`selected.columns` = c("Apple", "Pear", "Lemon"))
app$setInputs(do = "click")
app$setInputs(df_rows_current = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_rows_all = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_state = c(1660138079049, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$snapshot()
