app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$uploadFile(datafile = "example.csv")
app$setInputs(do = "click")
app$setInputs(df_rows_current = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_rows_all = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_state = c(1660142011178, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(`selected.columns` = "Apple")
app$setInputs(`selected.columns` = c("Apple", "Pear"))
app$setInputs(`selected.columns` = c("Apple", "Pear", "Lemon"))
app$setInputs(do = "click")
app$setInputs(df_rows_current = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_rows_all = c(1, 2, 3, 4), allowInputNoBinding_ = TRUE)
app$setInputs(df_state = c(1660142014386, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$snapshot()
app$snapshot()
app$snapshot()
