# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_datefixR_wrappers", use_symbols = TRUE, package_name = "datefixR")

#' @usage NULL
#' @useDynLib datefixR, .registration = TRUE
NULL

#' Process French date strings by removing articles and normalizing ordinals
#' @noRd
process_french <- function(date) .Call(wrap__process_french, date)

#' Process Russian date strings by normalizing months
#' @noRd
process_russian <- function(date) .Call(wrap__process_russian, date)

#' Validate month imputation value
#' @noRd
imputemonth <- function(month_impute) .Call(wrap__imputemonth, month_impute)

#' Validate day imputation value
#' @noRd
imputeday <- function(day_impute) .Call(wrap__imputeday, day_impute)

#' Validate day imputation value range
#' @noRd
checkday <- function(day_impute) .Call(wrap__checkday, day_impute)

#' Main date fixing function - Rust implementation of .fix_date
fix_date <- function(date, day_impute, month_impute, subject, format, excel, roman_numeral) .Call(wrap__fix_date, date, day_impute, month_impute, subject, format, excel, roman_numeral)

#' Analyze and fix date strings in a whole column of a DataFrame
#' @noRd
fix_date_column <- function(dates, day_impute, month_impute, subjects, format, excel, roman_numeral) .Call(wrap__fix_date_column, dates, day_impute, month_impute, subjects, format, excel, roman_numeral)


# nolint end
