# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_french <- function(date) {
    .Call(`_datefixR_process_french`, date)
}

process_russian <- function(date) {
    .Call(`_datefixR_process_russian`, date)
}

imputemonth <- function(monthImpute_) {
    invisible(.Call(`_datefixR_imputemonth`, monthImpute_))
}

imputeday <- function(dayImpute_) {
    invisible(.Call(`_datefixR_imputeday`, dayImpute_))
}

checkday <- function(dayImpute) {
    invisible(.Call(`_datefixR_checkday`, dayImpute))
}

