name: "Auto message for PR's and Issues"

on: 
  pull_request:
    types: [opened]
  issues:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/first-interaction@v3
        with:
          issue-message: 'Thank you for opening your first issue for datefixR! @nathansam will reply as soon as possible'
          pr-message: 'Thank you for opening your first pull request! You will receive a response soon.'